[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_SUPABASE_URL = "YOUR_SUPABASE_URL"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"

# Next.js specific settings
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = false
[build.processing.js]
  bundle = false
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = false

# Netlify Edge configuration
[[edge_functions]]
  function = "next-server"
  path = "/*"

# Handle all Next.js paths
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/functions/next-image"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-api/:splat"
  status = 200

# SPA fallback - handles client-side routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next-server"
  status = 200

# Protect access to Supabase environment variables
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
